// A plain array of {cat, text} objects — add more anytime, no special format needed.
export const TIPS = [
  // ---- Measurement practice ----
  { cat: 'Measurement', text: 'Measure twice before recording a dimension — a single misread tape is the most common source of takeoff error.' },
  { cat: 'Measurement', text: "Record dimensions in the order you'll need them for squaring: length, then width, then height." },
  { cat: 'Measurement', text: 'Break an irregular shape into rectangles and triangles rather than estimating an average width.' },
  { cat: 'Measurement', text: 'On a sloped surface, the actual sloped length and its horizontal projection are not interchangeable — measure the one you need.' },
  { cat: 'Measurement', text: 'Note which face you measured from (internal, external, or centreline) — your method of measurement specifies one consistently.' },
  { cat: 'Measurement', text: "Check a laser distance meter's calibration before a measurement run, not after finishing one." },
  { cat: 'Measurement', text: "Round to the precision your method specifies — don't state false precision beyond what you actually measured." },
  { cat: 'Measurement', text: "Always check a drawing's stated scale rather than assuming it matches the last sheet you used." },
  { cat: 'Measurement', text: 'A drawing printed at the wrong size throws off every scaled measurement — check a known dimension against it first.' },
  { cat: 'Measurement', text: 'Measure openings (doors, windows) as voids separately from the wall area they interrupt.' },
  { cat: 'Measurement', text: 'For curved elements, measure the radius or diameter directly rather than estimating from a chord.' },
  { cat: 'Measurement', text: 'Flag an uncertain dimension for site verification rather than estimating and moving on silently.' },
  { cat: 'Measurement', text: 'Keep a running total as you go — errors are far easier to catch early than at the very end.' },
  { cat: 'Measurement', text: 'Sanity-check your total against a rough mental estimate: does that number look plausible for the space?' },
  { cat: 'Measurement', text: 'On multi-storey buildings, confirm floor-to-floor heights before assuming every level is identical.' },
  { cat: 'Measurement', text: "Take off from the most recent drawing revision — check the revision letter and date in the title block." },
  { cat: 'Measurement', text: 'Keep length, width and depth in the same unit before multiplying for a volume.' },
  { cat: 'Measurement', text: "Don't average irregular ground levels — take enough spot levels to represent the actual undulation." },
  { cat: 'Measurement', text: 'For "extra over" items, measure the base item fully, then measure only the incremental difference.' },
  { cat: 'Measurement', text: 'Know whether your method of measurement wants net (voids deducted) or gross quantities before you start.' },
  { cat: 'Measurement', text: 'Allow for laps and returns on membranes and insulation, not just the flat area.' },
  { cat: 'Measurement', text: "Photograph your measurement points on site where practical — a photo settles a dispute a memory can't." },
  { cat: 'Measurement', text: 'A steel tape stretches slightly under tension — apply the same tension each time for consistency.' },
  { cat: 'Measurement', text: 'When two sources give the same dimension (a scaled drawing and a printed figure), check them against each other.' },
  { cat: 'Measurement', text: 'Label a sketch with dimensions the moment you take them — memory fades faster than you expect.' },

  // ---- Site safety ----
  { cat: 'Safety', text: 'Never lean over an unprotected edge to take a measurement — use a laser, or ask for edge protection first.' },
  { cat: 'Safety', text: 'Check for overhead services before extending a survey pole or tape near power lines.' },
  { cat: 'Safety', text: 'High-visibility clothing and a hard hat are the minimum on any live site, however quick the visit.' },
  { cat: 'Safety', text: 'Confirm an excavation has been assessed for stability before entering it to measure.' },
  { cat: 'Safety', text: "Never enter a confined space without confirmed atmosphere testing and a permit in place." },
  { cat: 'Safety', text: "If a structure looks unstable, don't measure it — report it and wait for it to be made safe." },
  { cat: 'Safety', text: 'Wet or icy surfaces change your footing risk fast — slow down rather than rushing a measurement.' },
  { cat: 'Safety', text: "Keep a charged phone and know the site's assembly point before working alone." },
  { cat: 'Safety', text: "A tape measure's blade can cut under tension — retract it under control, not by letting it snap back." },
  { cat: 'Safety', text: 'Near moving plant, make eye contact with the operator before stepping into their path.' },
  { cat: 'Safety', text: 'A ladder should be footed or secured before you climb it to take a level.' },
  { cat: 'Safety', text: 'Report a near-miss during a site visit, even if nothing happened — patterns matter more than single incidents.' },
  { cat: 'Safety', text: "Site inductions exist for a reason — don't skip one because you're \"just measuring.\"" },
  { cat: 'Safety', text: 'Check the forecast before a visit involving work at height or near water.' },
  { cat: 'Safety', text: 'Dust and noise on an active site can mask hazards — stay alert, not just focused on the tape.' },
  { cat: 'Safety', text: 'Know the location of the nearest fire point and first-aider before starting work on an unfamiliar site.' },
  { cat: 'Safety', text: 'Never disable or bypass a guard or barrier to get a better measurement angle.' },
  { cat: 'Safety', text: 'PPE that has visible damage should be replaced, not "still good enough."' },
  { cat: 'Safety', text: 'Manual handling injuries are among the most common on site — lift with your legs, not your back.' },
  { cat: 'Safety', text: 'Two people measuring together should agree hand signals before working near noisy plant.' },

  // ---- Standard-method practice ----
  { cat: 'Practice', text: 'Keep your dimension sheet legible — someone else may need to check or continue it.' },
  { cat: 'Practice', text: 'Cross-reference every bill item back to the dimension sheet line it came from.' },
  { cat: 'Practice', text: 'Group items by work section as you go, rather than sorting everything at the end.' },
  { cat: 'Practice', text: 'Use consistent abbreviations across a project, noted once at the top of the sheet.' },
  { cat: 'Practice', text: 'Double-check units match before summing quantities together in an abstract.' },
  { cat: 'Practice', text: 'A good abstract makes billing almost mechanical — most errors happen upstream, in the takeoff itself.' },
  { cat: 'Practice', text: 'Keep rates and quantities in separate places so either can be updated independently.' },
  { cat: 'Practice', text: "Note assumptions directly on the dimension sheet, not just in your head." },
  { cat: 'Practice', text: 'Revisit your standard-item checklist for a section before calling it complete.' },
  { cat: 'Practice', text: "When a rate changes, update it once in your rate list — don't hunt through every project." },
  { cat: 'Practice', text: 'A dimension sheet is a working record, not just a means to a total — keep it able to be checked.' },
  { cat: 'Practice', text: 'Where a description is ambiguous, write it out in full rather than relying on a shorthand only you understand.' },
  { cat: 'Practice', text: 'Reconcile your final bill total against a rough early estimate — big gaps deserve an explanation.' },
  { cat: 'Practice', text: 'Keep drawing references against every measured item — it saves hours if a query comes back later.' },
  { cat: 'Practice', text: 'Separate preliminaries (site setup, management, welfare) clearly from measured work in your bill.' },

  // ---- Common mistakes ----
  { cat: 'Mistakes', text: 'Forgetting to deduct openings from a wall area before billing it.' },
  { cat: 'Mistakes', text: 'Mixing units within one calculation — some dimensions in mm, others in m.' },
  { cat: 'Mistakes', text: 'Taking off from an outdated drawing revision.' },
  { cat: 'Mistakes', text: 'Double-counting an item that appears on both a plan and a section drawing.' },
  { cat: 'Mistakes', text: 'Assuming symmetry in a building without checking — many "mirrored" wings differ subtly.' },
  { cat: 'Mistakes', text: 'Forgetting a wastage allowance on cut materials like tiles or timber.' },
  { cat: 'Mistakes', text: 'Billing net where the method requires gross, or the reverse.' },
  { cat: 'Mistakes', text: 'Confusing an "extra over" item with a full separate item, inflating the bill.' },
  { cat: 'Mistakes', text: 'Not recording which drawing and revision a dimension came from, making a later check impossible.' },
  { cat: 'Mistakes', text: 'Rounding too early in a calculation, letting small errors compound across many items.' },
  { cat: 'Mistakes', text: "Missing a repeated floor or element because a schedule wasn't cross-checked against the drawings." },
  { cat: 'Mistakes', text: 'Assuming a scale bar without checking it against a printed dimension on the same drawing.' },
  { cat: 'Mistakes', text: 'Failing to note that a rate excludes something (access, disposal) until it is too late to adjust.' },
  { cat: 'Mistakes', text: 'Treating a provisional sum as a fixed, final cost.' },
  { cat: 'Mistakes', text: "Skipping a site visit when drawings alone don't clarify existing conditions." },
  { cat: 'Mistakes', text: 'Forgetting to update a project-wide total after correcting a single row.' },
  { cat: 'Mistakes', text: 'Copying a rate from a similar past project without checking if specification or region changed.' },
  { cat: 'Mistakes', text: "Not distinguishing between a project's design drawings and its as-built drawings." },

  // ---- QS / construction terminology ----
  { cat: 'Terms', text: 'BOQ (Bill of Quantities): an itemized list of quantities and rates forming a priced schedule for a project.' },
  { cat: 'Terms', text: 'PC Sum (Prime Cost Sum): an allowance for work or goods not yet fully specified, adjusted later against actual cost.' },
  { cat: 'Terms', text: 'Provisional Sum: an estimated allowance for work that cannot be accurately defined at tender stage.' },
  { cat: 'Terms', text: 'Dayworks: work valued by time and materials rather than a fixed rate, usually for variations.' },
  { cat: 'Terms', text: 'Variation Order: a formally instructed change to the contracted scope of work.' },
  { cat: 'Terms', text: 'Retention: a percentage of payment withheld until defects are rectified, released in stages.' },
  { cat: 'Terms', text: 'Snagging: identifying minor defects near completion for the contractor to fix before handover.' },
  { cat: 'Terms', text: 'RFI (Request for Information): a formal query to the design team when information is missing or unclear.' },
  { cat: 'Terms', text: 'NRM (New Rules of Measurement): the RICS standard method of measurement widely used in the UK.' },
  { cat: 'Terms', text: 'SMM7: an older UK standard method of measurement, largely superseded by NRM.' },
  { cat: 'Terms', text: 'POMI: Principles of Measurement (International), used for international measurement conventions.' },
  { cat: 'Terms', text: 'Abstract: a summarised collection of like items from dimension sheets, ready for billing.' },
  { cat: 'Terms', text: 'Squaring: multiplying timesing and dimensions to arrive at a measured quantity.' },
  { cat: 'Terms', text: 'Timesing: the multiplier applied to a dimension for repeated identical items.' },
  { cat: 'Terms', text: 'Waste: an allowance added to a measured quantity for material lost in cutting or handling.' },
  { cat: 'Terms', text: 'Extra Over: additional cost for a feature that replaces part of a base item, billed as the difference only.' },
  { cat: 'Terms', text: 'DPC (Damp Proof Course): a barrier built into a wall to prevent rising damp.' },
  { cat: 'Terms', text: 'DPM (Damp Proof Membrane): a barrier under a floor slab to prevent moisture ingress.' },
  { cat: 'Terms', text: 'Substructure: all building work below ground floor level.' },
  { cat: 'Terms', text: 'Superstructure: all building work above substructure level.' },
  { cat: 'Terms', text: 'Practical Completion: the stage a building is substantially finished and usable, minor items aside.' },
  { cat: 'Terms', text: "Defects Liability Period: the period after completion when the contractor must fix defects." },
  { cat: 'Terms', text: 'Contingency Sum: an allowance for unforeseen costs, not tied to specific known work.' },
  { cat: 'Terms', text: 'Preliminaries: the cost of running a site — management, welfare, temporary works — not tied to measured work.' },
  { cat: 'Terms', text: "Overheads: a business's indirect costs, allocated across projects rather than one specific job." },
  { cat: 'Terms', text: "Fluctuations: a contractual mechanism adjusting prices for material or labour cost changes over time." },
  { cat: 'Terms', text: 'Interim Valuation: a periodic assessment of completed work, used to certify payment during a project.' },
  { cat: 'Terms', text: 'Final Account: the agreed total cost of a contract after all variations and adjustments.' },
  { cat: 'Terms', text: 'Cost Plan: an early budget breakdown by building element, used to control design cost.' },
  { cat: 'Terms', text: 'Elemental Cost Analysis: cost data broken down by building element, used for benchmarking.' },
  { cat: 'Terms', text: 'Take-off: the process of measuring quantities from drawings or site.' },
  { cat: 'Terms', text: 'Work Section: a grouping of related bill items, such as substructure or finishes.' },
  { cat: 'Terms', text: 'As-built Drawings: drawings updated to reflect what was actually constructed, not just designed.' },
  { cat: 'Terms', text: 'Retention Bond: a guarantee substituting for cash retention, released under agreed conditions.' },
  { cat: 'Terms', text: 'Liquidated Damages: pre-agreed compensation payable by the contractor for late completion.' },
  { cat: 'Terms', text: 'Method Statement: a document describing how a specific task will be carried out safely.' },
  { cat: 'Terms', text: 'RAMS: a combined Risk Assessment and Method Statement document.' },
  { cat: 'Terms', text: 'Setting Out: establishing the precise position of a structure on site from a drawing.' },
  { cat: 'Terms', text: 'Datum: a fixed reference point or level from which other measurements are taken.' },
  { cat: 'Terms', text: 'Benchmark: a surveyed point of known height, used as a reference for site levels.' },
  { cat: 'Terms', text: 'Formwork: temporary moulds used to shape wet concrete until it cures.' },
  { cat: 'Terms', text: 'Falsework: a temporary structure supporting formwork or an incomplete permanent structure.' },
  { cat: 'Terms', text: 'Rebar: reinforcing steel bars embedded in concrete for tensile strength.' },
  { cat: 'Terms', text: 'Screed: a level layer, usually cementitious, laid over a floor before final finishes.' },
  { cat: 'Terms', text: 'Blinding: a thin concrete layer laid to give a clean, level surface before further construction.' },
  { cat: 'Terms', text: 'Hardcore: compacted broken stone or aggregate used as a sub-base.' },
  { cat: 'Terms', text: 'Cavity Wall: a wall built as two skins with a gap between them, often insulated.' },
  { cat: 'Terms', text: 'Lintel: a horizontal structural member spanning an opening such as a door or window.' },
  { cat: 'Terms', text: 'Fire Rating: a classification of how long a building element resists fire before failing.' },
  { cat: 'Terms', text: 'U-value: a measure of heat loss through a building element — lower means better insulated.' },
  { cat: 'Terms', text: 'JCT: a common family of UK standard building contracts (Joint Contracts Tribunal).' },
  { cat: 'Terms', text: 'NEC: an alternative UK contract family emphasising collaborative project management.' },
  { cat: 'Terms', text: "Snag List: a documented list of individual defects to resolve before completion." },
  { cat: 'Terms', text: 'Provisional Quantity: an estimated quantity for work that can be measured properly only once started.' },
  { cat: 'Terms', text: 'Nominated Subcontractor: a specialist subcontractor selected by the client or designer, not the main contractor.' },
  { cat: 'Terms', text: 'Domestic Subcontractor: a subcontractor chosen and appointed directly by the main contractor.' },
  { cat: 'Terms', text: 'Value Engineering: reviewing a design to reduce cost while preserving required function and quality.' },
  { cat: 'Terms', text: 'Life Cycle Cost: the total cost of an asset including construction, operation, maintenance and disposal.' },

  // ---- Unit conversions & reference figures ----
  { cat: 'Conversions', text: '1 inch = 25.4 mm' },
  { cat: 'Conversions', text: '1 foot = 0.3048 m' },
  { cat: 'Conversions', text: '1 yard = 0.9144 m' },
  { cat: 'Conversions', text: '1 mile = 1.609 km' },
  { cat: 'Conversions', text: '1 m = 3.281 ft' },
  { cat: 'Conversions', text: '1 m² = 10.764 sq ft' },
  { cat: 'Conversions', text: '1 sq ft = 0.0929 m²' },
  { cat: 'Conversions', text: '1 acre = 4,046.86 m²' },
  { cat: 'Conversions', text: '1 hectare = 10,000 m² = 2.471 acres' },
  { cat: 'Conversions', text: '1 m³ = 35.31 cubic ft' },
  { cat: 'Conversions', text: '1 cubic yard = 0.7646 m³' },
  { cat: 'Conversions', text: '1 litre = 0.001 m³' },
  { cat: 'Conversions', text: '1 UK gallon = 4.546 litres' },
  { cat: 'Conversions', text: '1 US gallon = 3.785 litres' },
  { cat: 'Conversions', text: '1 kg = 2.205 lb' },
  { cat: 'Conversions', text: '1 tonne = 1,000 kg' },
  { cat: 'Conversions', text: '1 lb = 0.4536 kg' },
  { cat: 'Conversions', text: '1 kN = 224.8 lbf' },
  { cat: 'Conversions', text: '1 bar = 100 kPa' },
  { cat: 'Conversions', text: '1 psi = 6.895 kPa' },
  { cat: 'Conversions', text: 'Normal-weight concrete density is roughly 2,400 kg/m³.' },
  { cat: 'Conversions', text: 'Structural steel density is roughly 7,850 kg/m³.' },
  { cat: 'Conversions', text: 'Water density is 1,000 kg/m³ — a handy benchmark for estimating other materials.' },
  { cat: 'Conversions', text: 'A standard UK bag of cement is 25 kg.' },
  { cat: 'Conversions', text: 'A standard UK brick is roughly 215 × 102.5 × 65 mm.' },
  { cat: 'Conversions', text: 'A standard UK block is roughly 440 × 215 mm, in thicknesses of 100, 140 or 215 mm.' },
  { cat: 'Conversions', text: 'A4 paper is 210 × 297 mm; A3 is 297 × 420 mm; A1 is 594 × 841 mm; A0 is 841 × 1189 mm.' },
  { cat: 'Conversions', text: 'Common architectural drawing scales: 1:50, 1:100, 1:200 and 1:1250.' },
  { cat: 'Conversions', text: 'Common engineering drawing scales: 1:20, 1:25 and 1:500.' },
  { cat: 'Conversions', text: '1 m/s = 3.6 km/h — useful for converting site plant or wind speeds.' },
  { cat: 'Conversions', text: 'A standard UK internal door height is around 1,981 mm (6\'6").' },
  { cat: 'Conversions', text: 'A typical residential ceiling height is 2,400–2,700 mm.' },
  { cat: 'Conversions', text: '1 stone = 6.35 kg.' },
  { cat: 'Conversions', text: '1 degree = 0.01745 radians.' },
  { cat: 'Conversions', text: '1 nautical mile = 1.852 km.' },
  { cat: 'Conversions', text: '1 square metre = 1.196 square yards.' },
];
